---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: alertmgr-svc-for-minikube
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
    - protocol: TCP
      port: 9093 
