---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-svc-for-minikube
spec:
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
