---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus-svc-for-minikube
spec:
  selector:
    app: prometheus
    prometheus: prometheus-operator-prometheus    
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090 
